pipeline:
  build:
    image: openjdk:8
    commands:
      - ./gradlew clean build
      - ./gradlew test
    when:
     branch: master
  publish:
    image: plugins/ecr
    repo: vijayraghavan08/drone-demo
    tags:
      - "latest"
      - "commit_${DRONE_COMMIT}"
      - "build_${DRONE_BUILD_NUMBER}"
      - "${DRONE_BUILD_NUMBER}"
    when:
     branch: master
  #deploy_sit:
  #  image: quay.io/hectorqin/drone-kubectl
  #  kubernetes_template: /k8s/deployment.yaml
  #  kubernetes_namespace: dev
#     debug: true
  #  secrets: 
  #    - kubernetes_server
  #    - kubernetes_cert
  #    - kubernetes_token
  #  when:
  #    branch: master
  #prod_deply:
  #  image: quay.io/hectorqin/drone-kubectl
  #  kubernetes_template: /k8s/deployment.yaml
  #  kubernetes_namespace: dev
  #  debug: true
  #  secrets: 
  #    - kubernetes_server
  #    - kubernetes_cert
  #    - kubernetes_token
  #  when:
  #    branch: release
  
