# ---
# apiVersion: v1
# kind: Namespace
# metadata:
#   name: dev-space
---
apiVersion: v1
kind: "Service"
metadata:
  name: "drone-demo-service"
  namespace: "dev"
  labels:
    region: "dev"
spec:
  ports:
    - port: 8080
      targetPort: 8080
      name: http
  selector:
      app: "drone-demo"
  type: ClusterIP
---
apiVersion: v1
kind: "Deployment"
metadata:
  name: "drone-demo"
  namespace: "dev"
  labels:
    region: "dev"
    app: "drone-demo"
spec:
  replicas: 1
  # selector:
  #   matchLabels:
  #     region: "dev"
  template:
    metadata:
      labels:
        region: "dev"
        app: "drone-demo"
    spec:
      containers:
      - name: "drone-demo"
        image: "567651206748.dkr.ecr.us-east-1.amazonaws.com/drone-demo:latest"
        ports:
          - containerPort: 8080