apiVersion: v1
kind: "Service"
metadata:
  name: "drone-demo-service"
  namespace: "dev"
  labels:
    region: "dev"
    app: "drone-demo"
spec:
  ports:
    - port: 8080
      targetPort: 8080
      name: http
  selector:
      region: "dev"
      app: "drone-demo"
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: "Deployment"
metadata:
  name: "drone-demo"
  namespace: "dev"
  labels:
    region: "dev"
    app: "drone-demo"
spec:
  selector:
    matchLabels:
      app: "drone-demo"
  replicas: 1
  template:
    metadata:
      labels:
        app: "drone-demo"
    spec:
      containers:
      - name: drone-demo
        image: "567651206748.dkr.ecr.us-east-1.amazonaws.com/drone-demo:latest"
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
