apiVersion: "v1"
kind: "Service"
metadata:
  name: "sb-drone-demo-service"
  namespace: "dev"
  labels:
    region: "dev"
spec:
  ports:
    - port: 8080
      targetPort: 8080
      name: http
  selector:
      app: "sb-drone-demo"
  type: ClusterIP
---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  name: "sb-drone-demo"
  namespace: "dev"
  labels:
    region: "dev"
    app: "sb-drone-demo"
    repo: ${DRONE_REPO_NAME}
    commit: ${DRONE_COMMIT_SHA}
    build: "build_7"
spec:
  replicas: 1
  # selector:
  #   matchLabels:
  #     region: "dev"
  template:
    metadata:
      labels:
        region: "dev"
        app: "sb-drone-demo"
    spec:
      containers:
      - name: "sb-drone-demo"
        image: "567651206748.dkr.ecr.us-east-1.amazonaws.com/drone-demo:build_7"
        ports:
          - containerPort: 8080